Refactor update_content_metadata and reindex_algolia
openedx/enterprise-catalog pull request #131
Opened 2020-06-11 17:08 UTC by adamstankiewicz

## Description

Coming soon!

## Ticket Link

[ENT-2661](https://openedx.atlassian.net/browse/ENT-2661)

## Post-review

Squash commits into discrete sets of changes

2020-06-11 18:34 UTC, adamstankiewicz commented on enterprise_catalog/apps/api/tasks.py
> +def update_full_content_metadata_task(*args, **kwargs):
TODO: docstring

2020-06-11 19:05 UTC, chavesj commented on enterprise_catalog/apps/api_client/discovery.py
> +                courses += response.get('results', [])
here's another block of repeated code that can be broken out into a utility method (see lines 107-112)

2020-06-11 19:05 UTC, chavesj commented on enterprise_catalog/apps/catalog/management/commands/reindex_algolia.py
> +        logger.info(message)
some serious cleanup here 🧽  🙂

2020-06-11 19:05 UTC, chavesj commented on enterprise_catalog/apps/catalog/management/commands/reindex_algolia.py
> +        index_enterprise_catalog_courses_in_algolia_task.delay(
(This comment applies to every call to delay()) - delay() returns an AsyncResult object which contains the task ID. It's probably worth logging the task ID in your message below

2020-06-11 19:05 UTC, chavesj commented on enterprise_catalog/apps/api/tasks.py
> +        logger.error(message, COURSE)
this can be broken out into a method since it's used both here and in update_full_content_metadata_task

2020-06-12 16:46 UTC, bbaker6225 reviewed
Looks good overall, just a few small comments

2020-06-12 16:46 UTC, bbaker6225 commented on enterprise_catalog/settings/base.py
> +CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', '')
Is this set in edx-internal already?

2020-06-12 16:46 UTC, bbaker6225 commented on enterprise_catalog/apps/catalog/models.py
> +    # also part of at least one EnterpriseCatalog
Nit: Might be worth turning this comment into a docstring for the overall method?

2020-06-12 16:46 UTC, bbaker6225 commented on enterprise_catalog/apps/catalog/management/commands/update_content_metadata.py
> +        # with the full course metadata from /courses/.
I imagine it's fine, but just want to check and see if you've run into any issue with potentially updating the same `ContentMetadata` at the same time since different queries can reference the same metadata

2020-06-12 16:48 UTC, chavesj approved these changes
LGTM 🚀

2020-06-12 16:50 UTC, chavesj requested changes

2020-06-12 16:50 UTC, chavesj commented on enterprise_catalog/settings/base.py
> +CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', '')
Good catch @bbaker6225 , need a PR in edx-internal before this can be merged

2020-06-12 16:55 UTC, adamstankiewicz commented on enterprise_catalog/apps/catalog/management/commands/update_content_metadata.py
> +        # with the full course metadata from /courses/.
Yeah, I haven't come across this issue in testing locally, but it also crossed my mind. It shouldn't have any impact on the association logic since that's still unique for each `CatalogQuery`. The create/update of `ContentMetadata` records should also be fine. If one task creates a new `ContentMetadata` record, another task would then just be updating the newly created one.

2020-06-12 16:55 UTC, bbaker6225 commented on enterprise_catalog/apps/api/tasks.py
> +        metadata_record.json_metadata = course_metadata
Are there any fields that we might be losing here that we want? To name one, I think `aggregation_key` is only on the search endpoints and I believe we use that

2020-06-12 16:57 UTC, adamstankiewicz commented on enterprise_catalog/settings/base.py
> +CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', '')
@bbaker6225 Ah, right. Any guidance on what the value of this would be for stage/prod?

2020-06-12 17:05 UTC, adamstankiewicz commented on enterprise_catalog/apps/api/tasks.py
> +        metadata_record.json_metadata = course_metadata
Hmm, within enterprise-catalog, we only use `aggregation_key` for the /search/all endpoint and parsing its results. Nothing within enterprise-catalog relies on that field existing within `json_metadata` on ContentMetadata records.

That said, I'm unsure off the top of my head about the downstream impacts of no longer including `aggregation_key`. If it's no longer included, callers of the `get_content_metadata` endpoint will no longer `aggregation_key` (or any other search-only fields).

I will look into this more, and follow-up.

2020-06-12 17:05 UTC, bbaker6225 commented on enterprise_catalog/settings/base.py
> +CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', '')
I'm seeing `'redis://edx-prod-queues.6sxrym.ng.0001.use1.cache.amazonaws.com:6379'` as the value elsewhere (such as for VEM). I'm pretty sure that's the shared one that we want to use, but it's probably worth throwing a question in the sre channel to check

2020-06-12 18:01 UTC, chavesj commented on enterprise_catalog/settings/base.py
> +CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', '')
another option: since the result backend will always be the same as the broker URL you can just move this statement below the BROKER_URL string formatting statement and set it equal to BROKER_URL. Wouldn't need an edx-internal PR that way

2020-06-12 18:07 UTC, brittneyexline commented on enterprise_catalog/apps/api/tasks.py
> +        metadata_record.json_metadata = course_metadata
i would grep for aggregation key in the edx-enterprise to see if anything there depends on it, since that is the main internal production code that uses get_content_metadata. otherwise i don't see it being a big deal. alternatively, you could merge the dictionaries and write that value instead of overwriting entirely.

2020-06-12 18:20 UTC, adamstankiewicz commented on enterprise_catalog/settings/base.py
> +CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', '')
Updated!

2020-06-12 18:31 UTC, adamstankiewicz commented on enterprise_catalog/apps/api/tasks.py
> +        metadata_record.json_metadata = course_metadata
The only use of `aggregation_key` within edx-enterprise seems to be in tests, e.g. creating fake API responses from the catalog details endpoint (or `get_content_metadata` equivalent in enterprise-catalog).

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/2828721/84535045-04f03600-acb9-11ea-9b56-612bcacebf8e.png">

From this, I don't believe edx-enterprise necessarily depends on it. That said, the transmit_content_metadata job currently sends `aggregation_key` to our integrated channels (e.g., Degreed). That job depends on `get_content_metadata` and the data within `json_metadata`. 

Given that we are sending this data to 3rd party systems, it probably makes sense to merge the dictionaries in case any of our customers rely on `aggregation_key`.

2020-06-12 18:36 UTC, bbaker6225 commented on enterprise_catalog/apps/api/tasks.py
> +        metadata_record.json_metadata = course_metadata
Yeah I agree that we might as well merge dictionaries

2020-06-12 18:45 UTC, chavesj approved these changes
noice, celery settings looking much cleaner 🧽

2020-06-12 19:30 UTC, adamstankiewicz commented on enterprise_catalog/apps/api/tasks.py
> +        metadata_record.json_metadata = course_metadata
Updated! It now merges original json_metadata with new course_metadata to not remove any potentially critical keys.

2020-06-12 19:41 UTC, adamstankiewicz commented
@bbaker6225 @chavesj tagged you both on an edx-internal PR (https://github.com/edx/edx-internal/pull/2136) to add a non-recurring Jenkins job for the new management command `update_full_content_metadata` in case we ever need to run it.

2020-06-12 20:11 UTC, merged