Adding dev.dd.{} targets to Makefile
openedx/enterprise-catalog pull request #169
Opened 2020-08-26 18:25 UTC by jinder1s

We needed some way to differentiating a command that only works with decentralized devstack(DD). My solution is dev.dd prefix to a command. For example, to build app image for DD, you need: dev.dd.build.  I choose this method cause it seemed like the smallest change necessary for people to start working with DD

My assumptions: any dev.{} command should either work for both DD and normal devstack or just for devstack. For dev.{} commands that only work with normal devstack, there will be DD equivalent.

Problems I see with this approach: there is no way to specifying a command only works on normal devstack.

2020-08-26 18:26 UTC, jinder1s commented on Makefile
> +	docker-compose down
I could not find a downing command, so I assumed this was a typo

2020-08-26 19:22 UTC, timmc-edx commented on Makefile
> +def.dd.pull:
```suggestion
dev.dd.pull:
```

typo

2020-08-26 19:24 UTC, kdmccormick requested changes
As I mentioned in Slack, I'm in favor of any of these:
1. Drop the `dev.` prefix, and just use `make dd.{}`
2. Drop the prefixes altogether. `make up`, `make shell`, `make pull-images`, etc. Nice and clean!
3. Don't even use Makefile targets. Almost all of these can be made into very simple docker-compose commands (`docker-compose up`, `docker-compose build`, `docker-compose pull`, etc.). I honestly think that we insulate people from learning how Docker and Docker Compose work by wrapping up these commands. It also allows us to let the commands get more complicated instead of fixing the underlying issues.

2020-08-26 19:24 UTC, kdmccormick commented on Makefile
> +	docker-compose down --volumes && docker-compose pull --include-deps app
You do not want `docker-compose down --volumes` here. That's synonymous with `make destroy`

2020-08-26 19:28 UTC, timmc-edx commented
I am totally in favor of just using docker-compose commands directly rather than Makefile targets if they don't add too much verbosity. Makefile targets add discoverability, but I'm happy to leave that to a wiki page or versioned howto doc somewhere, since people will mostly need to know _workflows_, not individual targets anyhow. The other thing they add is a consistent interface, which is a more interesting benefit. But papering over differences in how different IDAs do devstack might not be a good thing.

If we do use Makefile targets, though... With centralized devstack, I don't think the prefixes make sense. But given that in DD, these targets have to coexist with other Makefile targets e.g. `requirements` and `clean`, a short prefix of some sort makes sense for setting them apart.

2020-08-26 19:33 UTC, timmc-edx commented
We'll also need to add all of these targets to the `.PHONY` list.

2020-08-26 19:38 UTC, kdmccormick commented
Btw, here is a shell script that I use to generate `.PHONY` declarations, in case you find it helpful :) https://github.com/kdmccormick/home/blob/master/scripts/src/make-phonies

It assumes that every Makefile target is phony.

2020-08-27 13:44 UTC, jinder1s commented
@timmc-edx @kdmccormick You guys have mostly convinced me. I am now onboard with asking folks to use docker-compose directly rather than go through make. I'm planning on bringing this up at arch tea time today, so please come to give futher input.  In the meantime, I'm gonna create a ticket to create a how-to doc which has a list of docker commands someone will need to use for DD. Final Note: this is definitely up for debate based on what input we get during prototyping.

2020-08-27 13:44 UTC, closed without merging