feat: ENT-5119 Added additional fields in Algolia index for Programs
openedx/enterprise-catalog pull request #343
Opened 2021-11-04 14:15 UTC by irfanuddinahmad

## Description

This PR adds additional fields for in the Algolia index for Programs. The additional fields are Availability, Partners, Subjects, Skills, Level Types

## Ticket Link

[ENT-5119](https://openedx.atlassian.net/browse/ENT-5119)

2021-11-08 12:46 UTC, HammadAhmadWaqas requested changes

2021-11-08 12:46 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +    if program_type and program_type.get('slug') == 'masters':
I think `program_type` will be string, So is this  `program_type.get('slug') == 'masters'` expression right?

2021-11-08 12:46 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +    return list(availability)
Line 405 (return _('Available now')) returning a single item and here we are returning a list, 
Should not availability a single item always?

2021-11-08 12:46 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +            'programs': list(get_program_type(searchable_product)),
Why we are adding programs here? we have an existing key `program_type` to represent the type of the program.

2021-11-08 12:46 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/tests/test_algolia_utils.py
> +    def test_get_program_availability(self, program_metadata, expected_availability):
Are we checking availability for `Master` programs? as it is mentioned they are a little different!

2021-11-08 12:46 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +    return max(set(level_types), key=level_types.count) if level_types else ''
why we have used `set` here? 
can we use default param to empty value like: `max(level_types, default='', key=level_types.count)` ?

2021-11-08 12:46 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +            'program_titles': list(get_program_title(searchable_product)),
why we are typecasting to list? program title should not be a singular value?

2021-11-08 13:56 UTC, irfanuddinahmad commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +    if program_type and program_type.get('slug') == 'masters':
Fixed.

2021-11-08 13:57 UTC, irfanuddinahmad commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +    return list(availability)
This is conforming to the course availability ... which is a list

2021-11-08 14:00 UTC, irfanuddinahmad commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +            'programs': list(get_program_type(searchable_product)),
We want to use the same facet for courses and programs. This already exists for courses.

2021-11-08 14:00 UTC, irfanuddinahmad commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +    return max(set(level_types), key=level_types.count) if level_types else ''
We want to the find the "mode" of the list.

2021-11-08 14:01 UTC, irfanuddinahmad commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +            'program_titles': list(get_program_title(searchable_product)),
We want to use the same field as is used for courses.

2021-11-10 08:30 UTC, HammadAhmadWaqas approved these changes
LGTM

2021-11-10 10:39 UTC, muhammad-ammar approved these changes
LGTM

2021-11-10 11:49 UTC, merged