feat: new backend API for default course views
openedx/enterprise-catalog pull request #383
Opened 2022-01-21 17:00 UTC by alex-sheehan-edx

## Description

new api view to retrieve first four ranked courses under a catalog in algolia. 

## Ticket Link

Link to the associated ticket
[5241](https://openedx.atlassian.net/browse/ENT-5241)

## Post-review

Squash commits into discrete sets of changes

2022-01-21 19:42 UTC, kiram15 requested changes
My main thing is just to make it flexible enough that it will also be able to accommodate the future api calls for default programs as well

2022-01-21 19:42 UTC, kiram15 commented on enterprise_catalog/apps/api/v1/tests/test_views.py
> +        'partners': [
Programs are a little different, authoring_orginization is more reliable way to show who the program is written by, because some programs in prod don't even have an associated partner.

2022-01-21 19:42 UTC, kiram15 commented on enterprise_catalog/apps/api/v1/views.py
> +        'availability',
Maybe check with Binod that you have all the variables that will be eventually needed for program modal? (course_keys, price, program_type, etc)

2022-01-21 22:58 UTC, alex-sheehan-edx commented on enterprise_catalog/apps/api/v1/views.py
> +        'availability',
is price an option for programs currently? 🤔

2022-01-24 15:54 UTC, binodpant commented on enterprise_catalog/apps/api/v1/views.py
> +        'availability',
I indicated to. Alex that I am going to call discovery to get course details for program anyway so the price is already also in that response so I should have what I need AFAICT already (course keys, the what you will learn stuff (subtitle), and total program price, are in discovery response)

2022-01-24 15:57 UTC, binodpant commented on enterprise_catalog/apps/api/v1/views.py
> +            f'enterprise_catalog_query_titles:{facets.get("enterprise_catalog_query_titles")[0]}',
do we only ever want to use the first of these query titles?

2022-01-24 18:18 UTC, alex-sheehan-edx commented on enterprise_catalog/apps/api/v1/views.py
> +            f'enterprise_catalog_query_titles:{facets.get("enterprise_catalog_query_titles")[0]}',
yeah, the hope is that only one query title is provided

2022-01-24 18:25 UTC, johnnagro reviewed
I think I'd prefer large refactors (moving view classes into dedicated files) to be separated into distinct PRs from from functionality changes. It makes it hard to pick out whats new functionality versus just new organization.

I also want to know if we've considered just re-using the front-end algolia client to make a call without a query/facets for the top 4 results, versus introducing a dedicated api? its a lot of extra surface area to maintain, as well as keeping the JSON response structures in some degree of parity, right?

2022-01-24 18:33 UTC, johnnagro commented on enterprise_catalog/apps/api/v1/views/default_catalog_results.py
> +    def validate_query_facets(self, facets):
i pulled these into `export_utils` to DRY up their use in the CSV exporter classes. You could re-use.

2022-01-24 18:33 UTC, johnnagro commented on enterprise_catalog/apps/api/v1/views/default_catalog_results.py
> +    def querydict_to_dict(self, query_dict):
i pulled these into `export_utils` to DRY up their use in the CSV exporter classes. You could re-use.

2022-01-24 18:33 UTC, johnnagro commented on enterprise_catalog/apps/api/v1/views/default_catalog_results.py
> +            return Response(f'Error: invalid facet(s): {invalid_facets} provided.', status=HTTP_400_BAD_REQUEST)
should this be JSON formatted? ie machine readable?

2022-01-24 18:35 UTC, johnnagro commented on enterprise_catalog/apps/api/v1/views.py
> +        'availability',
price is available in algolia for courses, we should put it into programs documents in algolia too imo.

2022-01-24 19:54 UTC, binodpant commented on enterprise_catalog/apps/api/v1/views.py
> +        'availability',
yup so clarified in chat. The pull I am doing from discovery is going to be for only one program at a time, when the modal opens, it won't be for listing views like here. I agree though that for list/search use cases, we should leverage algolia when we can, we can discuss post this PR what options we can go with

2022-01-24 19:55 UTC, binodpant commented on enterprise_catalog/apps/api/v1/views.py
> +        'availability',
also I need to pull more than just price, there is course subtitles, course image etc. Adding all that to algolia may or may not be desirable, something we can also chat more about

2022-01-25 18:29 UTC, kiram15 approved these changes

2022-01-25 18:49 UTC, merged