feat: ENT-5364 Added pathway indexing for Algolia
openedx/enterprise-catalog pull request #396
Opened 2022-02-05 03:47 UTC by irfanuddinahmad

## Description

This PR adds Pathways type content metadata to the Algolia search index

## Ticket Link

[ENT-5364](https://openedx.atlassian.net/browse/ENT-5364)

2022-02-07 08:55 UTC, HammadAhmadWaqas requested changes

2022-02-07 08:55 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/api/tasks.py
> +        indexable_content_keys = indexable_course_keys + indexable_program_keys + indexable_pathways_keys
Can we do it in 1 line?
```
indexable_pathways_keys = ContentMetadata.objects.filter(content_type=PATHWAY). distinct().values_list('content_key', flat=True)
```

2022-02-07 08:55 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +            course_metadata = ContentMetadata.objects.filter(content_key=course.get('key')).first()
can we use `get_pathway_course_keys ` and `get_pathway_program_uuids ` utilities and query the database only once to get all the records?

2022-02-07 08:55 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +def get_pathway_skill_names(pathway):
I have added skills in search/all so we don't need to get skills again here.

2022-02-07 08:55 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +        })
I think we also add information like, `language`, `partners `, `subjects `, `level_type ` `banner_image`

2022-02-07 14:55 UTC, irfanuddinahmad commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +            course_metadata = ContentMetadata.objects.filter(content_key=course.get('key')).first()
Can you elaborate?

2022-02-07 14:56 UTC, irfanuddinahmad commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +        })
how are these defined for a pathway?

2022-02-07 14:59 UTC, irfanuddinahmad commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +        })
Do we need the banner in the index?

2022-02-08 09:47 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +            course_metadata = ContentMetadata.objects.filter(content_key=course.get('key')).first()
Right now you are making database queries in a loop. We can query only once and process all those content metadata.

2022-02-08 09:48 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +        })
The same way we are getting them for programs. And yes we need that image on the Pathways card.

2022-02-08 09:49 UTC, HammadAhmadWaqas reviewed
Queries Answered

2022-02-08 10:59 UTC, irfanuddinahmad commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +        })
I think we need to define the level_type and language for a pathway ...

2022-02-08 13:51 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +        })
I think we can get it same way we are getting in Program

2022-02-09 13:22 UTC, HammadAhmadWaqas approved these changes

2022-02-09 13:23 UTC, merged

2022-02-09 14:18 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +def get_pathway_partners(pathway):
Wo have partner field in pathways own object.

2022-02-09 14:19 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/tests/test_algolia_utils.py
> +
Do we need to remove this commented code?