WIP -- Added a new task to load missing programs metadata into the database.
openedx/enterprise-catalog pull request #401
Opened 2022-02-08 09:46 UTC by saleem-latif

## Description
Update command update_content_metadata from enterprise-catalog repo to save pathways content metadata as it is saving for programs and courses

## Ticket Link

Link to the associated ticket
[ENT-5362](https://openedx.atlassian.net/browse/ENT-5362)

## Post-review

Squash commits into discrete sets of changes

2022-02-09 09:02 UTC, HammadAhmadWaqas requested changes
please add the `include_learner_pathways` flag in search all query param as requested is the ticket.

2022-02-09 09:02 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/api/tasks.py
> +            program_uuids.update([item.get('key') for item in learner_pathway_metadata.get('programs', set())])
Please use this utility defined here https://github.com/openedx/enterprise-catalog/pull/396/files#diff-f95d821947945f8e3094ac125b397892d0f51cf2f2169c01dec21f9d0c080633R359
`get_pathway_course_keys` `get_pathway_program_uuids`

2022-02-09 09:02 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/constants.py
> +
value should be `learnerpathway `
please add this in CONTENT_TYPE_CHOICES

2022-02-09 10:45 UTC, saleem-latif commented on enterprise_catalog/apps/api/tasks.py
> +            program_uuids.update([item.get('key') for item in learner_pathway_metadata.get('programs', set())])
Okay 👍 , I will add this once the PR containing those methods is merged.

2022-02-09 10:53 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/api/tasks.py
> +            program_uuids.update([item.get('key') for item in learner_pathway_metadata.get('programs', set())])
actually that PR is dependent on your PR. can you copy that utility in your code and when we will rebase, we will resolve conflicts.

2022-02-09 10:56 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/constants.py
> +    (LEARNER_PATHWAY, 'Learner Pathway'),
Do we need migration for this change?

2022-02-09 11:07 UTC, saleem-latif commented on enterprise_catalog/apps/catalog/constants.py
> +    (LEARNER_PATHWAY, 'Learner Pathway'),
Good catch, yes I will add a migration for this as well.

2022-02-10 09:02 UTC, HammadAhmadWaqas requested changes

2022-02-10 09:02 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/api/tasks.py
> +        'key': list(missing_program_uuids),
What if there is no missing key? I think we should not simply proceed if there is no missing key as it will create a dummy query daily.
Same should be true for `fetch_missing_course_metadata_task`

2022-02-10 09:02 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/api/tasks.py
> +        defaults={'content_filter': content_filter, 'title': None},
Can use create a Generic `title` here inserted of None, As it can help us trace queries that are created automatically.
example: `Auto-generated query to fetch_missing_pathway_metadata`

2022-02-10 09:02 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/api/tasks.py
> +        defaults={'content_filter': content_filter, 'title': None},
Same as above.
Also should we consider make this change in old similar task?

2022-02-10 09:02 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +    return list(program_uuids)
Why we are creating these utilities again? Should not it be already in the feature branch?

2022-02-10 09:44 UTC, HammadAhmadWaqas requested changes
Also, can we fix similar issues in fetch_missing_course_metadata_task as well?
What would you suggest?

2022-02-10 09:44 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/constants.py
> -PATHWAY = 'learnerpathway'
There is still one reference here enterprise_catalog/apps/catalog/algolia_utils.py with the old name

2022-02-10 09:44 UTC, HammadAhmadWaqas commented on enterprise_catalog/apps/catalog/constants.py
> +
nit: can we remove this space?

2022-02-10 09:55 UTC, HammadAhmadWaqas approved these changes

2022-02-10 09:58 UTC, merged