fix: formatting registration date in the csv download endpoint
openedx/enterprise-catalog pull request #556
Opened 2023-01-13 18:31 UTC by alex-sheehan-edx

## Description

registration date needs to be formatted m-d-y and placed after end date

## Ticket Link

Link to the associated ticket
https://2u-internal.atlassian.net/browse/ENT-6676

## Post-review

* [ ] Squash commits into discrete sets of changes
* [ ] Ensure that once the changes have been [deployed to stage](https://gocd.tools.edx.org/go/pipeline/activity/stage-enterprise_catalog), prod is manually deployed

2023-01-13 18:41 UTC, marlonkeating requested changes
Code looks good!  Add some unit tests for the new logic, and it should be good to go.

2023-01-20 20:42 UTC, johnnagro approved these changes

2023-01-20 20:42 UTC, johnnagro commented on enterprise_catalog/apps/api/v1/export_utils.py
> +        formatted_enroll_by = None
maybe put this before the `try` - initialize `formatted_enroll_by` to `None`

2023-01-20 20:57 UTC, marlonkeating approved these changes
Tests look good!

2023-01-23 15:17 UTC, merged