fix: use a different error handler
openedx/enterprise-catalog pull request #633
Opened 2023-06-27 20:17 UTC by johnnagro

## Description

I am not getting the behavior i expect. This makes two changes, first is uses a different error handler because I modified the read error handler, where perhaps i should be doing the connection error handler because they treat the error state differently. The read error one also looks at the status code and the exceptions i am interested in do not have a status.

Second is to explicitly set the read and connect retry counts. The docs say the total takes precedence but I cannot find where the read and connect counts are set if not in the init.

https://github.com/urllib3/urllib3/blob/main/src/urllib3/util/retry.py#L460-L472

2023-06-27 21:30 UTC, marlonkeating requested changes

2023-06-27 21:30 UTC, marlonkeating commented on enterprise_catalog/apps/api_client/base_oauth_with_retry.py
> +            logger.info('EnterpriseRetry retries exhausted.')
Does this give enough logging info for us to know the context?

2023-06-27 21:30 UTC, marlonkeating commented on enterprise_catalog/apps/api_client/base_oauth_with_retry.py
> +            connect=max_retries,
Where is max_retries defined?

2023-06-28 13:08 UTC, iloveagent57 commented on enterprise_catalog/apps/api_client/base_oauth_with_retry.py
> +            connect=max_retries,
it's a parameter to `__init__()`

2023-06-28 13:11 UTC, iloveagent57 commented on enterprise_catalog/apps/api_client/base_oauth_with_retry.py
> +            logger.info('EnterpriseRetry retries exhausted.')
I _think_ we'd get the task id in the logs along with this line, which is probably enough to go on?

2023-06-28 13:14 UTC, iloveagent57 approved these changes

2023-06-28 13:53 UTC, marlonkeating approved these changes

2023-06-28 13:53 UTC, merged