feat: catalog query filtering without elasticsearch
openedx/enterprise-catalog pull request #675
Opened 2023-09-21 18:00 UTC by johnnagro

## Description

Given a catalog query and some content metadata - can we determine if the content matches the query _without_ using Elasticsearch (ie `search/all`)? 

This will be useful when and if:
- crawl content once, determine catalogs from our copy (rather than re-crawl content for every query it belongs to)
- grind `search/all` less
- we want to process content metadata update events (from event bus)
- support catalog contents with similar query syntax but broader sources of content metadata (not everything in discovery)

- https://2u-internal.atlassian.net/browse/ENT-7712

2023-09-22 20:46 UTC, marlonkeating requested changes

2023-09-22 20:46 UTC, marlonkeating commented on enterprise_catalog/apps/catalog/filters.py
> +        return 'org__exclude'
nit: Could put this in a dict to reduce duplication and allow adding more cases without further stacking the elif tower
```suggestion
    corrections_for_typos = {
      'aggregation_key': ['aggregration__key', 'aggregation__key'],
      'org__exclude': ['org__exempt']
    }
    for correction, typos in corrections_for_typos.items():
      if raw_query in typos:
        return correction;
```

2023-09-22 20:46 UTC, marlonkeating commented on enterprise_catalog/apps/catalog/filters.py
> +    if len(raw_query_key.split("__")) == 2:
`raw_query_key.split("__")` expression gets duplicated a couple times
```suggestion
    field__comparison = raw_query_key.split("__")
    if len(field__comparison) == 2:
```

2023-09-22 20:46 UTC, marlonkeating commented on enterprise_catalog/apps/catalog/filters.py
> +                field_result = all(field_results)
Should the logic be reversed here?  I would expect 'exact' matching to require matching all results.

2023-09-25 19:05 UTC, johnnagro commented on enterprise_catalog/apps/catalog/filters.py
> +                field_result = all(field_results)
its confusing but "exact" in this case is really mean to be more like "includes" so any of them need to match. if the course key is "edX+Demo" and the query key is like "course_key: [ "edX+Demo", "MIT+Demo"]" you'd want this to match where as the else case is an "excludes" which means NONE of them can match... lemme think about the right way to document this and/or if we need to code this so its easier to understand.

2023-09-27 18:49 UTC, marlonkeating approved these changes

2023-09-28 19:44 UTC, merged