ENT-7544: Added new app academy with related models
openedx/enterprise-catalog pull request #705
Opened 2023-10-30 10:50 UTC by saleem-latif

## Description
An Academy backend is composed of multiple catalogs of learning content mapped as a single level tree of nodes. Each node stores a catalog query as a definition of content included in the node.
An academy will be associated with content metadata similar to how an enterprise is associated with content metadata.
Create the single tree based data model. [catalog queries](https://github.com/openedx/enterprise-catalog/blob/5d965def3355d3ff285d8389d4f1d5972ffc9849/enterprise_catalog/apps/catalog/models.py#L56) to reside on the nodes of the Academy.

## Ticket Link
[Academies app in enterprise catalog](https://openedx.atlassian.net/browse/ENT-7544)

## Post-review

* [ ] Squash commits into discrete sets of changes
* [ ] Ensure that once the changes have been [deployed to stage](https://gocd.tools.edx.org/go/pipeline/activity/stage-enterprise_catalog), prod is manually deployed

2023-11-01 14:29 UTC, irfanuddinahmad requested changes

2023-11-01 14:29 UTC, irfanuddinahmad commented on enterprise_catalog/apps/academy/models.py
> +    enterprise_catalogs = models.ManyToManyField(EnterpriseCatalog)
We should add long and short description.

2023-11-01 14:29 UTC, irfanuddinahmad commented on enterprise_catalog/apps/academy/models.py
> +    enterprise_catalogs = models.ManyToManyField(EnterpriseCatalog)
Please add a related_name for the reverse relationship e.g.
`enterprise_catalogs = models.ManyToManyField(EnterpriseCatalog, related_name='academies')`

2023-11-02 09:19 UTC, irfanuddinahmad approved these changes
LGTM!

2023-11-02 09:20 UTC, muhammad-ammar approved these changes
LGTM

2023-11-02 09:22 UTC, merged