feat: ENT-7554 Added academies in Algolia index
openedx/enterprise-catalog pull request #724
Opened 2023-11-24 13:38 UTC by irfanuddinahmad

## Description

This PR adds the academy uuids and associated tags to the Algolia index

## Ticket Link

Link to the associated ticket
[ENT-7918](https://2u-internal.atlassian.net/browse/ENT-7918)

## Post-review

* [ ] Squash commits into discrete sets of changes
* [ ] Ensure that once the changes have been [deployed to stage](https://gocd.tools.edx.org/go/pipeline/activity/stage-enterprise_catalog), prod is manually deployed

2023-11-26 07:14 UTC, irfanuddinahmad commented on enterprise_catalog/apps/api/tasks.py
> -        for course_metadata in program_to_courses_mapping[program_content_key]:
This 'for' loop seems like a remnant of a past refactoring ... seems to just add unnecessary cycles

2023-11-27 18:59 UTC, pwnage101 requested changes

2023-11-27 18:59 UTC, pwnage101 commented on enterprise_catalog/apps/api/tasks.py
> +            associated_catalogs = catalog_query.enterprise_catalogs.prefetch_related('academies').all()
I think you might want to move this prefetch outside the "first pass".  The way this function was originally designed, all SQL queries are invoked before the first pass (at the beginning of this function), and only O(1) SQL statements.
Can you try updating the `all_catalog_queries` definition (see other comment)?

2023-11-27 18:59 UTC, pwnage101 commented on enterprise_catalog/apps/api/tasks.py
>      all_catalog_queries = CatalogQuery.objects.prefetch_related('enterprise_catalogs')
I think this should become:
```suggestion
    all_catalog_queries = CatalogQuery.objects.prefetch_related('enterprise_catalogs', 'enterprise_catalogs__academies')
```

2023-11-27 19:01 UTC, pwnage101 commented on enterprise_catalog/apps/api/tasks.py
> -        for course_metadata in program_to_courses_mapping[program_content_key]:
I agree, thanks for catching

2023-11-27 19:02 UTC, pwnage101 commented on enterprise_catalog/apps/api/tasks.py
>      all_catalog_queries = CatalogQuery.objects.prefetch_related('enterprise_catalogs')
hopefully this prevents SQL fetches below inside the first pass when you retrieve the academy of a catalog.

2023-11-28 09:26 UTC, irfanuddinahmad commented on enterprise_catalog/apps/api/tasks.py
> +            associated_catalogs = catalog_query.enterprise_catalogs.prefetch_related('academies').all()
Done

2023-11-28 09:26 UTC, irfanuddinahmad commented on enterprise_catalog/apps/api/tasks.py
>      all_catalog_queries = CatalogQuery.objects.prefetch_related('enterprise_catalogs')
Done

2023-11-28 17:59 UTC, pwnage101 requested changes
almost there

2023-11-28 17:59 UTC, pwnage101 commented on enterprise_catalog/apps/api/tests/test_tasks.py
> +        assert ' 14 products found.' in products_found_log_records[0]
This is not your problem to solve, but can you at least add a note here explaining that the count should really only be "9 products found", but 5 additional algolia products are generated by the test course from self.setUp()?  That extra course is present in the test database and polluting our test numbers whenever the tests don't need it.

2023-11-28 17:59 UTC, pwnage101 commented on enterprise_catalog/apps/api/tasks.py
> +                    associated_academy_tags = academy.tags.all()
welp, looks like another thing to add to the prefetch: `enterprise_catalogs__academies__tags`

2023-11-28 17:59 UTC, pwnage101 commented on enterprise_catalog/apps/api/tasks.py
> +    )
```suggestion
    all_catalog_queries = CatalogQuery.objects.prefetch_related(
        'enterprise_catalogs',
        'enterprise_catalogs__academies',
        'enterprise_catalogs__academies__tags',
    )
```

I also wonder how to only fetch the columns we need, like tag titles and academy UUIDs.  I spent 5 minutes trying to look that up but couldn't find a solution.

2023-11-29 11:37 UTC, irfanuddinahmad commented on enterprise_catalog/apps/api/tasks.py
> +    )
Not too many columns expected in this Tag model. Also, we only expect to have at most 6-7 academies over the design life of this feature.

2023-11-29 11:39 UTC, irfanuddinahmad commented on enterprise_catalog/apps/api/tests/test_tasks.py
> +        assert ' 14 products found.' in products_found_log_records[0]
Done

2023-11-29 11:39 UTC, irfanuddinahmad commented on enterprise_catalog/apps/api/tasks.py
> +                    associated_academy_tags = academy.tags.all()
Done

2023-11-29 17:05 UTC, pwnage101 approved these changes

2023-11-29 17:05 UTC, pwnage101 commented on enterprise_catalog/apps/api/tasks.py
> +        'enterprise_catalogs__academies__tags'
nit: use trailing slashes on multi-line argumens

2023-12-05 09:13 UTC, merged