feat: adding course review metrics to content metadata and algolia index
openedx/enterprise-catalog pull request #735
Opened 2023-12-20 22:16 UTC by alex-sheehan-edx

## Ticket Link

Link to the associated ticket
https://2u-internal.atlassian.net/browse/ENT-8126

## Post-review

* [ ] Squash commits into discrete sets of changes
* [ ] Ensure that once the changes have been [deployed to stage](https://gocd.tools.edx.org/go/pipeline/activity/stage-enterprise_catalog), prod is manually deployed

2024-01-04 18:48 UTC, kiram15 approved these changes
LGTM! 🚢

2024-01-04 18:59 UTC, johnnagro requested changes

2024-01-04 18:59 UTC, johnnagro commented on enterprise_catalog/apps/api_client/tests/test_discovery.py
> +        assert 'Retrieving course reviews from course-discovery for page 1...' in mock_logger.info.call_args.args[0]
asserting log lines is less preferable than asserting the mocks are called with a specific input or some outcome/side-effect is observed

2024-01-04 18:59 UTC, johnnagro commented on enterprise_catalog/apps/api_client/discovery.py
> +        Makes a request to discovery's /api/v1/course_review/ paginated endpoint
is this endpoint paginated?

2024-01-04 18:59 UTC, johnnagro commented on enterprise_catalog/apps/api/tasks.py
> +            if review := reviews_for_courses_dict.get(content_key):
`reviews_for_courses_dict` is a list?

2024-01-04 20:08 UTC, alex-sheehan-edx commented on enterprise_catalog/apps/api_client/discovery.py
> +        Makes a request to discovery's /api/v1/course_review/ paginated endpoint
locally testing it seems so?

2024-01-04 20:23 UTC, alex-sheehan-edx commented on enterprise_catalog/apps/api/tasks.py
> +            if review := reviews_for_courses_dict.get(content_key):
nope- `get_course_reviews` should return a dictionary

2024-01-04 20:25 UTC, alex-sheehan-edx commented on enterprise_catalog/apps/api_client/tests/test_discovery.py
> +        assert 'Retrieving course reviews from course-discovery for page 1...' in mock_logger.info.call_args.args[0]
Removed for a mock called assertion

2024-01-05 16:08 UTC, johnnagro approved these changes

2024-01-05 16:13 UTC, merged