BOM-1401 : Upgrade edx-drf-extensions
openedx/enterprise-catalog pull request #74
Opened 2020-03-12 12:02 UTC by mzulqarnain1

Relevant JIRA : [https://openedx.atlassian.net/browse/BOM-1401](https://openedx.atlassian.net/browse/BOM-1401)

2020-03-12 13:54 UTC, Ayub-Khan requested changes

2020-03-12 13:54 UTC, Ayub-Khan commented on requirements/base.in
> +drf-jwt==1.14.0
use the constraints.txt file

2020-03-13 10:33 UTC, Ayub-Khan approved these changes

2020-03-13 10:33 UTC, Ayub-Khan commented on requirements/constraints.txt
> +drf-jwt==1.14.0
add a comment. that we are not currently supporting the latest version.

2020-03-13 11:47 UTC, jmbowman reviewed
This still needs the settings change mentioned in the edx-drf-extensions 4.0.1 release notes: https://github.com/edx/edx-drf-extensions/releases/tag/4.0.1

2020-03-13 12:03 UTC, jmbowman approved these changes

2020-03-13 12:09 UTC, merged