feat: indexing bayesian average ranking for courses in algolia
openedx/enterprise-catalog pull request #749
Opened 2024-01-24 17:50 UTC by alex-sheehan-edx

https://2u-internal.atlassian.net/browse/ENT-8193

## Post-review

* [ ] Squash commits into discrete sets of changes
* [ ] Ensure that once the changes have been [deployed to stage](https://gocd.tools.edx.org/go/pipeline/activity/stage-enterprise_catalog), prod is manually deployed

2024-01-25 21:52 UTC, johnnagro requested changes
okay so, close but imho i'd tweal things a bit:
- i'd calculate and set a constant default that is roughly correct in `base.py`
- i'd make a "get_global_average" that tries to read from cache then falls back
- i'd make a "calculate_and_set_global_average" and call that from a simple mgmt task

2024-01-25 21:52 UTC, johnnagro commented on enterprise_catalog/settings/base.py
> +ONE_DAY = ONE_HOUR * 24
i'd make this much, much longer - maybe "forever"

2024-01-25 21:52 UTC, johnnagro commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +    cache_key = DISCOVERY_AVERAGE_COURSE_REVIEW_CACHE_KEY
i'd break this out into a getter function that falls back to a settings value. the global average isnt going to move much, i'd calculate it by hand and add it to the base.py settings as the fallback

2024-01-25 21:52 UTC, johnnagro commented on enterprise_catalog/apps/api_client/discovery.py
> +            cache.set(cache_key, total_average_course_rating, settings.DISCOVERY_AVERAGE_COURSE_REVIEW_CACHE_TIMEOUT)
i'd break this out into its own function rather than include it in the reviews getter

2024-01-25 22:08 UTC, bcitro commented on enterprise_catalog/apps/api_client/discovery.py
> +            total_average_course_rating = rolling_rating_sum / len(results)
I think you also need to factor in the number of reviews for each course to get the true global average.  So in your rolling sum you'd want to include (`avg_course_rating` * `reviews_count`), and then ultimately divide by the sum of `reviews_count`.

2024-01-25 22:08 UTC, bcitro commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +    total_average_rating = cache.get(cache_key)
I think here we had talked about calculating the current global review average and falling back to that as a default if this cache key isn't set. From this snowflake query I calculated that to be `4.5`:

`SELECT SUM(REVIEWS_COUNT * AVG_COURSE_RATING)/SUM(REVIEWS_COUNT) FROM enterprise.course_reviews`

2024-01-25 22:08 UTC, bcitro commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +        bayes_avg = ((avg_review * ratings_count) + (total_average_rating * 15)) / (ratings_count + 15)
I would make `15` a constant

2024-01-26 18:58 UTC, johnnagro approved these changes
some suggestions but overall 👍

2024-01-26 18:58 UTC, johnnagro commented on enterprise_catalog/apps/catalog/algolia_utils.py
> +    total_average_rating = cache.get(cache_key)
ah i see now that we can pass the default into the getter, so you could do:
`cache.get(cache_key, COURSE_REVIEW_BASE_AVG_REVIEW_SCORE)`
then you wouldnt need the `if None` check later

2024-01-26 18:58 UTC, johnnagro commented on enterprise_catalog/apps/catalog/management/commands/tests/test_set_global_average_course_rating_value.py
> +            settings.DISCOVERY_AVERAGE_COURSE_REVIEW_CACHE_TIMEOUT,
according to the docs, if you pass `None` as the timeout, it will cache forever:
> The timeout argument is optional and defaults to the timeout argument of the appropriate backend in the [CACHES](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-CACHES) setting (explained above). It’s the number of seconds the value should be stored in the cache. Passing in None for timeout will cache the value forever. A timeout of 0 won’t cache the value.

https://docs.djangoproject.com/en/4.2/topics/cache/#django.core.cache.cache.set

2024-01-26 18:59 UTC, alex-sheehan-edx commented on enterprise_catalog/apps/catalog/management/commands/tests/test_set_global_average_course_rating_value.py
> +            settings.DISCOVERY_AVERAGE_COURSE_REVIEW_CACHE_TIMEOUT,
Forever sounds ok to me ¯\_(ツ)_/¯

2024-01-29 14:06 UTC, merged