OPS-4596 | Standard/Productionizing Dockerfile
openedx/enterprise-catalog pull request #75
Opened 2020-03-12 22:05 UTC by christopappas

## Description

Description of changes made

## Ticket Link

Link to the associated ticket
[Link title](https://openedx.atlassian.net/browse/ENT-XXXX)

## Post-review

Squash commits into discrete sets of changes

2020-03-13 13:57 UTC, coryleeio commented on Dockerfile
> +
Be sure to add the Gunicorn config and Gunicorn default command for a production centric file

Gunicorn handles large amounts of traffic better than a run server as the run server is single threaded to make debugging easier.

Notes should have an example of both of these things

2020-03-13 13:58 UTC, coryleeio commented on Dockerfile
>  EXPOSE 18161
I would expose the production centric ports instead of the dev centric ports

Keep in mind that the expose directive by itself doesn't actually do anything, it's just documentation.

I would document the production ready ports instead of the runserver ones, as these are typically only used in the development environment.  You can still use these development ports in the docker compose file.

In general think of the docker-compose file as the development part, and make the docker file for the production application when possible.

2020-03-13 13:59 UTC, christopappas commented on Dockerfile
> +
Alright 👍 -- yeah I wasn't sure if that was notes specific. I will look to adapt that

2020-03-13 14:01 UTC, christopappas commented on Dockerfile
>  EXPOSE 18161
Awesome, will do

2020-03-13 14:02 UTC, coryleeio commented on Dockerfile
>  EXPOSE 18161
The reasoning for this is that if you misconfigure an application it's usually better to launch a battle hardened production config by default then to launch a dev server, which may have security / encryption turned off, maybe it will have debugger ports open, stuff like that

2020-03-13 14:03 UTC, coryleeio commented on Dockerfile
>  EXPOSE 18161
Exposing both development and production would also be reasonable, especially with a comment saying what is for what.

Typically we use like
18160
18161 for dev
8160
8161 for prod...

I would prefer them be the same, but that's not what we've done historically.

You could also just make the run server use the same ports as production and that would make a lot of this simpler...

2020-03-13 21:38 UTC, christopappas commented on Dockerfile
> +
I think the above comments are more readable formatted like this. Hopefully I'm not breaking a linter rule or something..

2020-03-13 21:51 UTC, christopappas commented on enterprise_catalog/docker_gunicorn_configuration.py
> +bind = "0.0.0.0:8160"
so we do have a celery worker container specified in docker-compose.yml, which builds using the same Dockerfile. Not sure how running the app with gunicorn affects this, but wanted to say words before I leave this afternoon so I remember to come back to it.

2020-03-16 20:25 UTC, jdmulloy requested changes

2020-03-16 20:25 UTC, jdmulloy commented on .travis.yml
> +    script: make test
```suggestion
```
This is an override, since most jobs are ```make test```we could make it the default script and only override the script on the few that are different

```

Maybe something more like this
```
python: 3.5

script:
  - make test

matrix:
  include:
    - env: TOXENV=django111
    - env: TOXENV=django20
    - env: TOXENV=django21
    - env: TOXENV=django22
    - env: TESTNAME=quality
      script:
        - make quality
        - make pii_check
    - env: TESTNAME=translations
      script:
        - make validate_translations
```

diff
```
diff --git a/.travis.yml b/.travis.yml
index c927441..575e1f5 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,26 +1,23 @@
 language: python
+
+python: 3.5
+
+script:
+  - make test
+
 matrix:
   include:
-  - python: 3.5
-    env: TOXENV=django111
-    script: make test
-  - python: 3.5
-    env: TOXENV=django20
-    script: make test
-  - python: 3.5
-    env: TOXENV=django21
-    script: make test
-  - python: 3.5
-    env: TOXENV=django22
-    script: make test
-  - python: 3.5
-    env: TESTNAME=quality
-    script:
-    - make quality
-    - make pii_check
-  - python: 3.5
-    env: TESTNAME=translations
-    script: make validate_translations
+    - env: TOXENV=django111
+    - env: TOXENV=django20
+    - env: TOXENV=django21
+    - env: TOXENV=django22
+    - env: TESTNAME=quality
+      script:
+        - make quality
+        - make pii_check
+    - env: TESTNAME=translations
+      script:
+        - make validate_translations
 sudo: false
 branches:
   only:
```

2020-03-16 20:25 UTC, jdmulloy commented on Makefile
> +travis_docker_auth:
NIT: I would move this block below docker_build

2020-03-18 15:09 UTC, christopappas commented on enterprise_catalog/docker_gunicorn_configuration.py
> +bind = "0.0.0.0:8160"
i tested locally, and was able to confirm that the app container could talk to the worker container without anhy issues

2020-03-18 15:10 UTC, christopappas commented on enterprise_catalog/docker_gunicorn_configuration.py
> +"""
This is copy-pasted from https://github.com/edx/edx-notes-api/blob/master/notesserver/docker_gunicorn_configuration.py (with exception of changing the bind port)

2020-03-18 16:39 UTC, coryleeio commented on Dockerfile
> +
Can you symlink python3 so you can just call 'python' instead of 'python3'
https://github.com/edx/ecommerce/blob/coryleeio/dockerfile/Dockerfile#L9-L10

2020-03-18 16:39 UTC, coryleeio commented on Dockerfile
> +
You're good, they're just comments, change as you like

2020-03-18 16:39 UTC, coryleeio commented on Dockerfile
> +
and pip, same thing

2020-03-18 16:40 UTC, coryleeio commented on Dockerfile
> +CMD gunicorn --reload --workers=2 --name enterprise_catalog -b :18160 -c /edx/app/enterprise_catalog/enterprise_catalog/enterprise_catalog/docker_gunicorn_configuration.py --log-file - --max-requests
You can remove the binding and port form here if you like -b.

It's in the config also, and so it's unnecessary to have it here and there.

2020-03-18 16:40 UTC, coryleeio commented on Dockerfile
> +CMD gunicorn --reload --workers=2 --name enterprise_catalog -b :18160 -c /edx/app/enterprise_catalog/enterprise_catalog/enterprise_catalog/docker_gunicorn_configuration.py --log-file - --max-requests
I've been meaning to clean that up in notes

2020-03-18 16:41 UTC, christopappas commented on Dockerfile
> +CMD gunicorn --reload --workers=2 --name enterprise_catalog -b :18160 -c /edx/app/enterprise_catalog/enterprise_catalog/enterprise_catalog/docker_gunicorn_configuration.py --log-file - --max-requests
Binding is necessary to override the prod port that is set in the config

2020-03-18 16:41 UTC, christopappas commented on Dockerfile
> +CMD gunicorn --reload --workers=2 --name enterprise_catalog -b :18160 -c /edx/app/enterprise_catalog/enterprise_catalog/enterprise_catalog/docker_gunicorn_configuration.py --log-file - --max-requests
it's 8160 in the config file, but we want 18160 in dev env

2020-03-18 16:42 UTC, christopappas commented on Dockerfile
> +
cool, can do

2020-03-18 16:42 UTC, coryleeio approved these changes

2020-03-18 16:43 UTC, coryleeio commented on Dockerfile
> +CMD gunicorn --reload --workers=2 --name enterprise_catalog -b :18160 -c /edx/app/enterprise_catalog/enterprise_catalog/enterprise_catalog/docker_gunicorn_configuration.py --log-file - --max-requests
right, but this is the command used in the prod environment bc it's in the Dockerfile

2020-03-18 16:43 UTC, coryleeio commented on Dockerfile
> +CMD gunicorn --reload --workers=2 --name enterprise_catalog -b :18160 -c /edx/app/enterprise_catalog/enterprise_catalog/enterprise_catalog/docker_gunicorn_configuration.py --log-file - --max-requests
18160 is in docker-compose

2020-03-18 16:44 UTC, coryleeio commented on Dockerfile
> +CMD gunicorn --reload --workers=2 --name enterprise_catalog -b :18160 -c /edx/app/enterprise_catalog/enterprise_catalog/enterprise_catalog/docker_gunicorn_configuration.py --log-file - --max-requests
This is gunicorn, which isn't used in dev

2020-03-18 16:45 UTC, coryleeio commented on Dockerfile
> +CMD gunicorn --reload --workers=2 --name enterprise_catalog -b :18160 -c /edx/app/enterprise_catalog/enterprise_catalog/enterprise_catalog/docker_gunicorn_configuration.py --log-file - --max-requests
Ah yeah, so that port is wrong actually too

2020-03-18 16:45 UTC, coryleeio commented on Dockerfile
> +CMD gunicorn --reload --workers=2 --name enterprise_catalog -b :18160 -c /edx/app/enterprise_catalog/enterprise_catalog/enterprise_catalog/docker_gunicorn_configuration.py --log-file - --max-requests
Ooooh this is devapp

2020-03-18 16:45 UTC, coryleeio commented on Dockerfile
> +CMD gunicorn --reload --workers=2 --name enterprise_catalog -b :18160 -c /edx/app/enterprise_catalog/enterprise_catalog/enterprise_catalog/docker_gunicorn_configuration.py --log-file - --max-requests
So if thats the case, I would change the command to runserver here

2020-03-18 16:48 UTC, coryleeio commented on .travis.yml
> +- make requirements
Since you have a dev image you could use the dev image for running the tests, it would use the correct version of python and whatnot then without you having to remember to update it

2020-03-18 16:48 UTC, coryleeio commented on .travis.yml
> +- make requirements
You don't have to do this, but it's worth considering

2020-03-18 16:50 UTC, coryleeio commented on enterprise_catalog/settings/devstack.py
> +if 'console' not in LOGGING['loggers']['django']['handlers']:
You'll likely need to fix logging in production.py too, (I didn't look), I did it with settings in notes

2020-03-18 16:54 UTC, coryleeio commented on enterprise_catalog/settings/devstack.py
> +if 'console' not in LOGGING['loggers']['django']['handlers']:
but both should work for console logging, I had to change the get_logger function in production.py in notes to use settings instead of function parameters

https://github.com/edx/edx-notes-api/blob/master/notesserver/settings/yaml_config.py#L48

that's the function I had to change


It's possible you've already taken care of this in production.py, but if it is copied you'll run into it later when you deploy to prod so I am mentioning it.

2020-03-18 17:02 UTC, christopappas commented on Dockerfile
> +CMD gunicorn --reload --workers=2 --name enterprise_catalog -b :18160 -c /edx/app/enterprise_catalog/enterprise_catalog/enterprise_catalog/docker_gunicorn_configuration.py --log-file - --max-requests
so the motivation here is that I also changed docker-compose (albeit commented out right now) to use gunicorn in order to keep the dev and prod environments closer in how they are run. any reason we wouldn't want dev to use gunicorn?

2020-03-18 17:16 UTC, coryleeio commented on Dockerfile
> +CMD gunicorn --reload --workers=2 --name enterprise_catalog -b :18160 -c /edx/app/enterprise_catalog/enterprise_catalog/enterprise_catalog/docker_gunicorn_configuration.py --log-file - --max-requests
Ah okay I see,

I'll let you decide, but the difference is roughly this:
the django runserver will restart when code changes are made, and is single threaded.
Gunicorn will not restart on changes, and when you attach to a process to debug you'll probably have multiple worker threads going.

2020-03-18 17:30 UTC, christopappas commented on Dockerfile
> +CMD gunicorn --reload --workers=2 --name enterprise_catalog -b :18160 -c /edx/app/enterprise_catalog/enterprise_catalog/enterprise_catalog/docker_gunicorn_configuration.py --log-file - --max-requests
Cool. Yeah totally get that having multiple worker threads could be a point of trouble, although I did confirm the --reload flag worked on change with both worker processes ( pids 18 and 20, change observed and workers reloaded with pids 22 and 24):

<img width="1259" alt="Screen Shot 2020-03-18 at 1 22 17 PM" src="https://user-images.githubusercontent.com/7385292/76988778-ac103c00-691b-11ea-87e1-6fcc6e8c5a42.png">

The reason I am also leaning towards using gunicorn locally is that it exposed a bunch of issues (related to admin css and logging), which, while in production it might not being an issue, I imagine that having that parity between dev and prod would be really helpful.

I'm gonna say, let's try going forward with gunicorn for now on dev and if we get surprised by a bunch of pain points, we can always switch back to runserver

(Provided of course enterprise team in question is cool with this when they do their review)

2020-03-18 17:45 UTC, christopappas commented on enterprise_catalog/settings/devstack.py
> +if 'console' not in LOGGING['loggers']['django']['handlers']:
yeah there is an analogous logging function called in base.py in the settings in this project, but DEBUG is set to False at the point which it is called, and therefore 'console' is not added to handlers when running the container locally.

I assumed that production logging happened via log files (which would require no changes in this PR) so instead of refactoring how/when the LOGGER is created, I added that one line to devstack.py to allow for logging to happen in context of the dev container running a gunicorn command

2020-03-18 18:12 UTC, jdmulloy approved these changes

2020-03-18 19:40 UTC, coryleeio commented on Dockerfile
> +CMD gunicorn --reload --workers=2 --name enterprise_catalog -b :18160 -c /edx/app/enterprise_catalog/enterprise_catalog/enterprise_catalog/docker_gunicorn_configuration.py --log-file - --max-requests
That sounds fine to me, so long as it doesn't cause any issues in dev I would say it is more ideal to have the parity also :+1:

2020-03-18 19:41 UTC, coryleeio commented on enterprise_catalog/settings/devstack.py
> +if 'console' not in LOGGING['loggers']['django']['handlers']:
Production logging is via console in K8s, and in docker in general typically

2020-03-18 19:42 UTC, coryleeio commented on enterprise_catalog/settings/devstack.py
> +if 'console' not in LOGGING['loggers']['django']['handlers']:
If you just have everything log to console you can decide what you want to do with the logs externally to the application

2020-03-18 19:44 UTC, coryleeio commented on enterprise_catalog/settings/devstack.py
> +if 'console' not in LOGGING['loggers']['django']['handlers']:
https://12factor.net
is an oft cited resource for this sort of thing

#12 is about logging

#11 is about dev/prod parity which is also relevant. xD

2020-03-19 14:32 UTC, adamstankiewicz commented on Dockerfile
> +CMD gunicorn --reload --workers=2 --name enterprise_catalog -b :18160 -c /edx/app/enterprise_catalog/enterprise_catalog/enterprise_catalog/docker_gunicorn_configuration.py --log-file - --max-requests
@christopappas Yeah, testing this PR locally, I noticed that changes made in the code no longer triggers the app to restart. The downside of this is that we would have to manually restart the server for each code change made during development which could be a potential bottleneck. This was mentioned above by @coryleeio.

I do see that code changes are captured in the logs, where the worker reloads due to a modified file but it doesn't seem to trigger a restart:

![image](https://user-images.githubusercontent.com/2828721/77077852-2e583900-69cc-11ea-9c3c-158c3c66a1c0.png)

Seems we'll now have to run `docker-compose restart app` to see code changes reflected in the running app if we proceed with using gunicorn locally as opposed to Django's runserver.

2020-03-19 14:39 UTC, christopappas commented on Dockerfile
> +CMD gunicorn --reload --workers=2 --name enterprise_catalog -b :18160 -c /edx/app/enterprise_catalog/enterprise_catalog/enterprise_catalog/docker_gunicorn_configuration.py --log-file - --max-requests
hmm... mine does pick up code changes and I did not have to run a docker-compose command 🤔

2020-03-19 15:01 UTC, adamstankiewicz commented on Dockerfile
> +CMD gunicorn --reload --workers=2 --name enterprise_catalog -b :18160 -c /edx/app/enterprise_catalog/enterprise_catalog/enterprise_catalog/docker_gunicorn_configuration.py --log-file - --max-requests
Just following up here based on the Slack discussion:

* `docker-compose restart app` is necessary to reload the app for settings changes
* hot reloads are working for non-settings code changes.

I think this will be fine moving forward, given that settings changes are much less frequent than non-settings changes 👍

2020-03-19 15:23 UTC, adamstankiewicz approved these changes

2020-03-19 16:16 UTC, chavesj commented on Dockerfile
> +RUN pip3 install -r /edx/app/enterprise_catalog/enterprise_catalog/requirements/base.txt
do we need to install requirements from base here? I think everything from base.txt is replicated in production.txt

2020-03-19 16:24 UTC, christopappas commented on Dockerfile
> +RUN pip3 install -r /edx/app/enterprise_catalog/enterprise_catalog/requirements/base.txt
had a look, looks like production.in requires base.txt, so yeah you are right, production.txt would ultimately have everything base.txt does

I can drop this line 👍

2020-03-19 19:06 UTC, merged