feat: adding guard rails to content query association setter to prevent large negative deltas
openedx/enterprise-catalog pull request #829
Opened 2024-05-08 21:14 UTC by alex-sheehan-edx

https://2u-internal.atlassian.net/browse/ENT-8778
## Post-review

* [ ] Squash commits into discrete sets of changes
* [ ] Ensure that once the changes have been [deployed to stage](https://gocd.tools.edx.org/go/pipeline/activity/stage-enterprise_catalog), prod is manually deployed

2024-05-09 18:26 UTC, marlonkeating requested changes

2024-05-09 18:26 UTC, marlonkeating commented on enterprise_catalog/settings/base.py
> +CATALOG_CONTENT_ASSOCIATION_CONTENT_DELTA_CUTOFF = os.environ.get(
Can we get documentation for these variables?

2024-05-09 18:26 UTC, marlonkeating commented on enterprise_catalog/apps/catalog/models.py
> +                    f"metadata set length of:{existing_relations_size}. The updated is prevented"
```suggestion
                    f"metadata set length of:{existing_relations_size}. The update is prevented"
```

2024-05-09 18:26 UTC, marlonkeating commented on enterprise_catalog/apps/catalog/models.py
> +                    "associate_content_metadata_with_query hit the warning threshold while setting query: "
Spotting these messages in the logs might be easier if we prefaced the log lines here
```suggestion
                    "[CONTENT_DELTA_WARNING] associate_content_metadata_with_query hit the warning threshold while setting query: "
```

2024-05-09 18:26 UTC, marlonkeating commented on enterprise_catalog/apps/catalog/models.py
> +                    f"metadata set length of:{existing_relations_size}. The updated is prevented"
Could we log the percentage diff and the threshold we're working with?

2024-05-09 21:49 UTC, alex-sheehan-edx commented on enterprise_catalog/apps/catalog/models.py
> +                    f"metadata set length of:{existing_relations_size}. The updated is prevented"
the percent dif is just new / old. But I'm fine with logging the threshold.

2024-05-10 14:34 UTC, marlonkeating commented on enterprise_catalog/apps/catalog/models.py
> +                    f"{catalog_query} to a content metadata set of length of {new_relations_size} when it previous "
```suggestion
                    f"{catalog_query} to a content metadata set of length of {new_relations_size} when it previously "
```

2024-05-10 16:14 UTC, marlonkeating approved these changes

2024-05-10 16:14 UTC, marlonkeating commented on docs/decisions/0009-query-content-associations-guard-rails.rst
> +Content associations will not be updated in specific cases, causes stagnant data being displayed to customers. The
```suggestion
Content associations will not be updated in specific cases, causing stagnant data to be displayed to customers. The
```

2024-05-10 16:14 UTC, marlonkeating commented on docs/decisions/0009-query-content-associations-guard-rails.rst
> +more disruptive to the customer's experience than the to continue using old data. It is also intended that the check on
```suggestion
more disruptive to the customer's experience than to continue using old data. It is also intended that the check on
```

2024-05-10 17:43 UTC, iloveagent57 requested changes
This is a good idea, and the ADR is very useful, thank you!

2024-05-10 17:43 UTC, iloveagent57 commented on docs/decisions/0009-query-content-associations-guard-rails.rst
> +The `associate_content_metadata_with_query` method will now consider the size of the existing query/content association
in RST, you need double back-ticks to format something as "code". That is:
```
``associate_content_metadata_with-query``
```

2024-05-10 17:43 UTC, iloveagent57 commented on docs/decisions/0009-query-content-associations-guard-rails.rst
> +modified at time will ensure there is a direct and easy way to allow a large content associations update to go through.
nit: format as "``modified_at``" here to denote it as a field.

2024-05-10 17:43 UTC, iloveagent57 commented on enterprise_catalog/apps/catalog/models.py
> +    existing_relations_size = len(catalog_query.contentmetadata_set.all())
Hard blocker: switch to
```
catalog_query.contentmetadata_set.count()
```
so we don't load the entire CM set into memory.

2024-05-10 17:43 UTC, iloveagent57 commented on enterprise_catalog/apps/catalog/models.py
> +    if existing_relations_size > settings.CATALOG_CONTENT_ASSOCIATIONS_CONTENT_BASE_SIZE_CUTOFF:
nit: maybe `CATALOG_CONTENT_INCLUSION_GUARDRAIL_CONSIDERATION_FLOOR`
and `CATALOG_CONTENT_INCLUSION_GUARDRAIL_ALLOWABLE_DELTA` for these setting names?

2024-05-10 17:43 UTC, iloveagent57 commented on enterprise_catalog/apps/catalog/models.py
> +            # `CATALOG_CONTENT_ASSOCIATION_CONTENT_DELTA_CUTOFF` (80% as of May 8th 2024) of content items from the
nit: adding in the percentage as of some date is actually misleading - the reader should be forced to go lookup the current value, rather than being presented with an historical guess.

2024-05-10 17:43 UTC, iloveagent57 commented on enterprise_catalog/apps/catalog/models.py
> +                return [metadata.content_key for metadata in catalog_query.contentmetadata_set.all()]
Use `values_list('content_key', flat=True)` here since you only need the keys, which will be a much smaller result set.

2024-05-10 17:43 UTC, iloveagent57 commented on enterprise_catalog/apps/catalog/models.py
> +                LOGGER.warning(
nit: prefer to use `%s` in log strings instead of f-strings: https://docs.python.org/3/howto/logging.html#optimization

2024-05-10 17:43 UTC, iloveagent57 commented on enterprise_catalog/apps/catalog/tests/test_models.py
> +    def test_associate_content_metadata_with_query_guardrails(self, mock_client):
great job on a thorough test!

2024-05-10 17:43 UTC, iloveagent57 commented on enterprise_catalog/apps/catalog/models.py
> +    if existing_relations_size > settings.CATALOG_CONTENT_ASSOCIATIONS_CONTENT_BASE_SIZE_CUTOFF:
one more suggestion: move everything in this if-block to a helper function - it's a lot of code to read that doesn't have much bearing on the rest of the main logic.

2024-05-10 17:43 UTC, iloveagent57 commented on enterprise_catalog/settings/base.py
> +CATALOG_CONTENT_ASSOCIATION_CONTENT_DELTA_CUTOFF = os.environ.get(
nit: you don't need to use `os.environ` as part of your default anymore. you can do this in `base.py`:
```python
NEW_SETTING = 'my-default-value'
```
and over on the production/stage yaml config side of things, override the default in the environment with
```
NEW_SETTING: "my-production-value"
```

2024-05-10 18:02 UTC, alex-sheehan-edx commented on docs/decisions/0009-query-content-associations-guard-rails.rst
> +modified at time will ensure there is a direct and easy way to allow a large content associations update to go through.
technically the field on the table is `modified`

2024-05-10 18:02 UTC, alex-sheehan-edx commented on docs/decisions/0009-query-content-associations-guard-rails.rst
> +modified at time will ensure there is a direct and easy way to allow a large content associations update to go through.
let me use back-ticks and clean up the language a bit

2024-05-10 18:10 UTC, alex-sheehan-edx commented on enterprise_catalog/apps/catalog/models.py
> +                LOGGER.warning(
wow, I need to switch up my patterns 😅

2024-05-10 18:36 UTC, iloveagent57 approved these changes

2024-05-10 19:30 UTC, merged