feat: more restricted runs and contains_content_items logic
openedx/enterprise-catalog pull request #916
Opened 2024-08-21 15:24 UTC by iloveagent57

* contains_content_items endpoint now both utilize the same shared logic around restricted runs
    * contains_content_items top-level key returns true based on explicit content membership *or*
    membership in configured restricted runs mapping
    * The previous point implies that requests about restricted course runs
    will response with contains_content_items=true, even if the run is
    not tied directly to the catalog via ContentMetadata records.
    ENT-9386
## Post-review

* [ ] Squash commits into discrete sets of changes
* [ ] Ensure that once the changes have been [deployed to stage](https://gocd.tools.edx.org/go/pipeline/activity/stage-enterprise_catalog), prod is manually deployed

2024-08-21 15:25 UTC, iloveagent57 commented on enterprise_catalog/apps/catalog/api.py
> +    return serialized_data or None
No implementation changed here.

2024-08-21 15:28 UTC, iloveagent57 commented on enterprise_catalog/apps/api/v1/views/enterprise_customer.py
>              contains_content_items = catalog.contains_content_keys(course_run_ids + program_uuids)
BTW, I believe `EnterpriseCatalog.contains_content_keys()` implicitly does an ANY type of query, not an ALL type of query.

2024-08-21 15:28 UTC, iloveagent57 commented on enterprise_catalog/apps/api/v1/views/enterprise_customer.py
> +            if contains_content_items or contains_requested_restricted_items:
...hence why I'm using an `or` here and not `and`.

2024-08-21 16:13 UTC, pwnage101 commented on enterprise_catalog/apps/catalog/api.py
> +    return serialized_data or None
Why did I review this code in a separate PR and you're adding it again?

2024-08-21 20:12 UTC, pwnage101 requested changes

2024-08-21 20:12 UTC, pwnage101 commented on enterprise_catalog/apps/api/v1/views/enterprise_customer.py
> +            course_run_ids, customer_catalogs
I think after some more rubber ducking today, I think we might want to pass `catalogs_that_contain_course` to `get_restricted_runs_allowed_for_query()` instead of all of the customer's catalogs. This avoids needing to cover an edge case in the frontend where the parent course does not match the base query, but one of its restricted runs does. We would use help texts and documentation to guide ECS to only write custom filters that match both the course and any of its restricted runs.
```suggestion
        response_data[RESTRICTED_RUNS_ALLOWED_KEY] = get_restricted_runs_allowed_for_query(
            course_run_ids, catalogs_that_contain_course
```

2024-08-21 20:30 UTC, pwnage101 reviewed
The rest LGTM!

2024-08-22 14:22 UTC, adamstankiewicz approved these changes
LGTM, pending any test updates (happy to re-review once tests updated).

2024-08-22 14:22 UTC, adamstankiewicz commented on enterprise_catalog/apps/api/v1/views/enterprise_customer.py
> -        any_catalog_contains_content_items = False
[kudos] Nice cleanup of `any_catalog_contains_content_items`, and only relying on the empty vs. non-empty `catalogs_that_contain_course`.

2024-08-22 17:52 UTC, pwnage101 commented on enterprise_catalog/apps/api/v1/views/enterprise_customer.py
> +                catalog, course_run_ids,
Nit: since these are not always course run IDs, should we take this opportunity to rename this variable to something more generic, like content_keys?

2024-08-22 17:52 UTC, pwnage101 commented on enterprise_catalog/apps/api/v1/tests/test_enterprise_customer_views.py
> +    def test_restricted_course_disallowed_if_course_not_in_catalog(self):
I still feel like there's a test missing for the exact case I was thinking about.  Can you come up with a situation that returns contains_content_items = true, AND restricted_runs_allowed = None?

2024-08-22 18:00 UTC, pwnage101 commented on enterprise_catalog/apps/api/v1/tests/test_enterprise_customer_views.py
> +    def test_restricted_course_disallowed_if_course_not_in_catalog(self):
nevermind, this test (`test_restricted_course_disallowed_if_course_not_in_catalog`) is exactly what I had in mind. I got thrown off by the fact that the other test sends a course run to the endpoint.

2024-08-22 18:01 UTC, pwnage101 approved these changes

2024-08-22 18:22 UTC, pwnage101 commented on enterprise_catalog/apps/api/v1/views/enterprise_customer.py
> +                catalog, course_run_ids,
even if just in the scope of this function (i.e. no change to endpoint signature)

2024-08-22 18:28 UTC, iloveagent57 commented on enterprise_catalog/apps/catalog/api.py
> +    return serialized_data or None
This is no longer true - implementation has now changed to take both courses and course runs into account.

2024-08-22 18:35 UTC, merged